using UnityEngine;

namespace GachaRPG
{
    /// <summary>
    /// Manages the shared Soul resource for the player's team.
    /// Soul is generated by S1 basic attacks and spent on Soul Burn variants of skills.
    /// Soul belongs to the team — not to individual units.
    /// </summary>
    public class SoulManager
    {
        public int CurrentSoul  { get; private set; }
        public const int MaxSoul = 10;

        /// <summary>Fired whenever Soul changes. Params: (currentSoul, maxSoul)</summary>
        public event System.Action<int, int> OnSoulChanged;

        public SoulManager()
        {
            CurrentSoul = 0;
        }

        /// <summary>Adds Soul, clamping at MaxSoul.</summary>
        public void AddSoul(int amount)
        {
            if (amount <= 0) return;
            CurrentSoul = Mathf.Min(MaxSoul, CurrentSoul + amount);
            OnSoulChanged?.Invoke(CurrentSoul, MaxSoul);
            Debug.Log($"[Soul] +{amount} Soul → {CurrentSoul}/{MaxSoul}");
        }

        /// <summary>
        /// Attempts to spend Soul. Returns false (and spends nothing) if insufficient.
        /// </summary>
        public bool TrySpendSoul(int cost)
        {
            if (CurrentSoul < cost)
            {
                Debug.Log($"[Soul] Cannot spend {cost} Soul — only {CurrentSoul} available.");
                return false;
            }
            CurrentSoul -= cost;
            OnSoulChanged?.Invoke(CurrentSoul, MaxSoul);
            Debug.Log($"[Soul] -{cost} Soul → {CurrentSoul}/{MaxSoul}");
            return true;
        }

        /// <summary>
        /// Returns true if the unit can use the Soul Burn variant of the given skill.
        /// </summary>
        public bool CanSoulBurn(SkillData skill) =>
            skill != null && skill.hasSoulBurn && CurrentSoul >= skill.soulBurnCost;

        /// <summary>Resets Soul to zero (e.g. start of a new battle).</summary>
        public void Reset()
        {
            CurrentSoul = 0;
            OnSoulChanged?.Invoke(CurrentSoul, MaxSoul);
        }
    }
}
